version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://trilogy_user:trilogy_password@postgres:5432/trilogy_db
      - SESSION_SECRET=${SESSION_SECRET:-trilogy_session_secret}
    volumes:
      - media_data:/app/media
    restart: unless-stopped

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=trilogy_user
      - POSTGRES_PASSWORD=trilogy_password
      - POSTGRES_DB=trilogy_db
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U trilogy_user -d trilogy_db"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  db_data:
  media_data: