services:
  nginx:
    image: nginx:alpine
    container_name: trilogy_nginx
    ports:
      - "${PORT:-80}:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - upload_videos:/app/uploads/videos
      - upload_images:/app/uploads/images
      - upload_documents:/app/uploads/documents
      - upload_presentations:/app/uploads/presentations
      - upload_thumbnails:/app/uploads/thumbnails
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - trilogy_network

  app:
    build:
      context: .
      dockerfile: Dockerfile
    expose:
      - "5000"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      # Database configuration
      - DATABASE_URL=postgresql://${POSTGRES_USER:-trilogy_user}:${POSTGRES_PASSWORD:-postgres}@postgres:5432/${POSTGRES_DB:-trilogy_db}
      
      # Application configuration
      - NODE_ENV=${NODE_ENV:-production}
      - PORT=5000
      - SESSION_SECRET=${SESSION_SECRET:-trilogy_session_secret}
      - CORS_ALLOWED_ORIGINS=${CORS_ALLOWED_ORIGINS:-*}
      
      # Admin user configuration
      - ADMIN_EMAIL=${ADMIN_EMAIL:-admin@example.com}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD:-adminpassword}
      - ADMIN_USERNAME=${ADMIN_USERNAME:-admin}
      
      # Client user configuration
      - CLIENT_EMAIL=${CLIENT_EMAIL:-client@example.com}
      - CLIENT_PASSWORD=${CLIENT_PASSWORD:-demopassword}
      - CLIENT_USERNAME=${CLIENT_USERNAME:-client}
    volumes:
      - upload_videos:/app/uploads/videos
      - upload_images:/app/uploads/images
      - upload_documents:/app/uploads/documents
      - upload_presentations:/app/uploads/presentations
      - upload_thumbnails:/app/uploads/thumbnails
    restart: unless-stopped
    networks:
      - trilogy_network
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:5000/api/healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  postgres:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=${POSTGRES_USER:-trilogy_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-postgres}
      - POSTGRES_DB=${POSTGRES_DB:-trilogy_db}
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-trilogy_user} -d ${POSTGRES_DB:-trilogy_db}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      - trilogy_network

networks:
  trilogy_network:
    driver: bridge

volumes:
  db_data:
    name: trilogy_db_data
  upload_videos:
    name: trilogy_upload_videos
  upload_images:
    name: trilogy_upload_images
  upload_documents:
    name: trilogy_upload_documents
  upload_presentations:
    name: trilogy_upload_presentations
  upload_thumbnails:
    name: trilogy_upload_thumbnails